version: "3"

services:
  documentation:
    build:
      context: ./
      dockerfile: Dockerfile
    image: documentation:17
    container_name: "documentation"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    ports:
      - "3200:80"
    logging:
      driver: "json-file"
      options:
        max-size: "16m"
        max-file: "8"